; Script generated by Antigravity AI for Playlist Stuck on Repeat
; See Inno Setup documentation for details on creating script files!

#define MyAppName "Playlist Stuck on Repeat"
#define MyAppVersion "2026.0531rc1"
#define MyAppPublisher "Aethertenshi"
#define MyAppExeName "Playlist-stuck-on-repeat__Art2Framework.exe"
#define MyAppIconName "PSoR.ico"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5F8F6355-13B4-4B2E-BE6C-B45A77F21FEE}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=LICENSE.txt
; The OutputDir will be in the publish folder
OutputDir=publish
OutputBaseFilename=PSoR-v2026.0531rc1-win-x64-Setup
SetupIconFile={#MyAppIconName}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "publish\PSoR-v2026.0531rc1-win-x64\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\PSoR-v2026.0531rc1-win-x64\*"; DestDir: "{app}"; Excludes: "playlists,playlists\*,settings.json,songs_star_cache.json"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Dirs]
Name: "{app}\playlists"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppIconName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppIconName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
